### ISSUE TITLE
error

### ISSUE THREAD

**Issue by websinkwastaken** [mstfsnc/twitter-video-downloader#1]
When I load the extension in chrome by the source I get these following errors
`Failed to load extension
File
~\Desktop\src
Error
Could not load background script './background.bundle.js'.
Could not load manifest.`

**Comment by mstfsnc** [comment]
Sorry for the late response. You can select dist folder to load the extension. If there is no dist folder, you have to run the `npm i && npm run build` command from the terminal. I also committed a clean build to the dist folder, you can download the final version and load it directly.
